from django.urls import path
from .views import (
    home,
    api_auth_csrf,
    api_auth_login,
    api_auth_logout,
    api_auth_me,
    api_auth_register,
    api_post_detail,
    api_post_regenerate,
    api_post_tweets,
    api_posts_timeline,
    api_user_profile,
    sign_up,
    log_in,
    log_out_page,
    timeline_page,
    post_detail_page,
    delete_post_summary,
    welcome,
    ingest_scrape,
    api_scrape_and_ingest,
)

urlpatterns = [
    path("", home, name="home"),
    path("signup/", sign_up, name="signup"),
    path("login/", log_in, name="login"),
    path("logout/", log_out_page, name="logout_page"),
    path("welcome/", welcome, name="welcome"),
    path("timeline/", timeline_page, name="timeline_page"),
    path("post/<int:post_id>/", post_detail_page, name="post_detail_page"),
    path("post/<int:post_id>/delete/", delete_post_summary, name="delete_post_summary"),
    path("api/auth/csrf/", api_auth_csrf, name="api_auth_csrf"),
    path("api/auth/login/", api_auth_login, name="api_auth_login"),
    path("api/auth/register/", api_auth_register, name="api_auth_register"),
    path("api/auth/me/", api_auth_me, name="api_auth_me"),
    path("api/auth/logout/", api_auth_logout, name="api_auth_logout"),
    path("api/v1/posts/timeline", api_posts_timeline, name="api_posts_timeline"),
    path("api/v1/posts/<int:post_id>", api_post_detail, name="api_post_detail"),
    path("api/v1/posts/<int:post_id>/tweets", api_post_tweets, name="api_post_tweets"),
    path("api/v1/posts/<int:post_id>/regenerate", api_post_regenerate, name="api_post_regenerate"),
    path("api/v1/users/<str:username>", api_user_profile, name="api_user_profile"),
    path("api/ingest-scrape/", ingest_scrape, name="ingest_scrape"),
    path("api/scrape-and-ingest/", api_scrape_and_ingest, name="api_scrape_and_ingest"),
]
