# Generated by Django 5.2.11 on 2026-02-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('article', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('media', models.URLField(blank=True)),
            ],
        ),
    ]
